class Element{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.children=[];this.parent=null;this.listeners={};this.value=attrs.value||'';this.type=attrs.type||'text';this.checked=Object.hasOwn(attrs,'checked');this.isConnected=true;this.style={setProperty(k,v){this[k]=v}};this.dataset={};this.disabled=false;this.clientWidth=600;this.clientHeight=400;for(const [k,v] of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.className=attrs.class||'';this.id=attrs.id||'';this.classList={toggle:(name,on)=>{const s=new Set(this.className.split(' '));on?s.add(name):s.delete(name);this.className=[...s].join(' ')}};}
 set innerHTML(html){this.children=[];this.html=html;const stack=[this],re=/<(\/)?([\w-]+)([^>]*?)>/g;let m;while((m=re.exec(html))){if(m[1]){if(stack.length>1)stack.pop();continue}const attrs={};const ar=/([\w-]+)="([^"]*)"/g;let a;while((a=ar.exec(m[3])))attrs[a[1]]=a[2];const el=new Element(m[2],attrs);stack.at(-1).append(el);if(!['img','input','br','meta','hr'].includes(m[2])&&!m[3].endsWith('/'))stack.push(el)}}
 get innerHTML(){return this.html||''}append(el){el.parent=this;this.children.push(el)}remove(){if(this.parent)this.parent.children=this.parent.children.filter(e=>e!==this)}
 setAttribute(k,v){this.attrs[k]=v}getBoundingClientRect(){return {left:0,top:0,width:600,height:400}}addEventListener(type,fn){(this.listeners[type]||= []).push(fn)}removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(f=>f!==fn)}dispatchEvent(event){event.target=this;for(const fn of this.listeners[event.type]||[])fn(event);if(this['on'+event.type])this['on'+event.type](event)}focus(){this.focused=true;this.dispatchEvent({type:'focus'})}click(){this.onclick?.({target:this})}showModal(){this.open=true}close(){this.open=false}get parentElement(){return this.parent}setRangeText(text,start,end){this.value=this.value.slice(0,start)+text+this.value.slice(end);this.selectionStart=this.selectionEnd=start+text.length}
 matches(s){s=s.trim();const m=/^(\w+)?\[([\w-]+)(?:="([^"]*)")?\]$/.exec(s);if(m)return (!m[1]||this.tagName.toLowerCase()===m[1])&&Object.hasOwn(this.attrs,m[2])&&(m[3]===undefined||this.attrs[m[2]]===m[3]);if(s.startsWith('.'))return this.className.split(' ').includes(s.slice(1));if(s.startsWith('#'))return this.id===s.slice(1);return this.tagName.toLowerCase()===s}
 querySelectorAll(s){const out=[];const selectors=s.split(',');const walk=n=>{for(const c of n.children){if(selectors.some(s=>c.matches(s)))out.push(c);walk(c)}};walk(this);return out}
 querySelector(s){return this.querySelectorAll(s)[0]||null}
}
module.exports={Element};
