const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {Element}=require('./dom.cjs');
function editor(){const doc=new Element();doc.innerHTML=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const document={getElementById:id=>doc.querySelector('#'+id),createElement:tag=>new Element(tag),addEventListener(){}};const context=vm.createContext({document,console,structuredClone,Blob,Event:class{constructor(type){this.type=type}},localStorage:{getItem(){return null},setItem(){}},navigator:{},Image:class{},setTimeout(){},clearTimeout(){}});context.window=context;context.addEventListener=()=>{};for(const file of ['core','math-tools','library','genially','game','editor'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/'+file+'.js'),'utf8'),context);return {context,doc,$:id=>document.getElementById(id),section(name){doc.querySelector('[data-section="'+name+'"]').click()},eval(code){return vm.runInContext(code,context)}}}
test('all eleven sidebar sections open with working controls',()=>{const e=editor();for(const name of ['project','title','images','differences','tasks','style','hud','final','sounds','assets','decor']){e.section(name);assert.ok(e.$('settings').innerHTML.length>100);assert.equal(e.eval('section'),name)}assert.equal(e.doc.querySelectorAll('[data-section]').length,11)});
test('screen text and button controls update model and immediate preview',()=>{const e=editor();e.section('title');for(const [key,value] of [['titleScreen.button.background','#aabbcc'],['titleScreen.button.label','Вперёд!'],['titleScreen.button.glow',24],['titleScreen.titleSize',64],['titleScreen.backgroundOpacity',35]]){const input=e.doc.querySelector('[data-key="'+key+'"]');assert.ok(input);input.value=String(value);input.dispatchEvent({type:'input'});assert.equal(e.eval('p.'+key),value);assert.ok(e.$('preview').srcdoc.includes(String(value)))}e.section('final');e.$('view-lose').click();assert.equal(e.eval('screen'),'lose');assert.ok(e.doc.querySelector('[data-key="finalScreens.lose.button.label"]'));e.$('view-win').click();assert.equal(e.doc.querySelector('[data-key="finalScreens.showTitle"]'),null)});
test('custom hint quantities and button styles are bound',()=>{const e=editor();e.section('hud');const field=e.doc.querySelector('[data-key="hud.hints"]');field.value='25';field.dispatchEvent({type:'input'});assert.equal(e.eval('p.hud.hints'),25);assert.ok(e.doc.querySelector('[data-key="hud.hintButton.glow"]'));assert.ok(e.doc.querySelector('[data-key="hud.hintButton.background"]'))});
test('assets contains ready game pairs and decor remains separate',()=>{const e=editor();e.section('assets');assert.equal(e.doc.querySelectorAll('[data-library]').length,2);assert.equal(e.doc.querySelectorAll('[data-asset]').length,0);e.section('images');assert.equal(e.doc.querySelectorAll('[data-library]').length,2);e.section('decor');assert.equal(e.doc.querySelectorAll('[data-asset]').length,5)});
test('delete dialog is internal and cancellation preserves state',async()=>{const e=editor();e.eval("const id=DiffCore.uid();const t=DiffCore.task(id);p.tasks.push(t);p.differences.push({id,label:'Деталь',shape:'rect',x:.5,y:.5,w:.1,h:.1,linkedTaskId:t.id,difficulty:'normal'});");e.section('differences');const action=e.doc.querySelector('[data-delete]').onclick();assert.equal(e.$('confirm-dialog').open,true);assert.ok(!e.$('confirm-message').textContent.includes('github'));e.$('confirm-no').click();await action;assert.equal(e.eval('p.differences.length'),1);const action2=e.doc.querySelector('[data-delete]').onclick();e.$('confirm-yes').click();await action2;assert.equal(e.eval('p.differences.length'),0);e.$('undo').click();assert.equal(e.eval('p.differences.length'),1)});
test('math template inserts into the chosen question and updates project',()=>{const e=editor();e.eval("const id=DiffCore.uid();p.tasks.push(DiffCore.task(id));");e.section('tasks');const field=e.doc.querySelector('[data-key="tasks.0.question"]');field.focus();e.doc.querySelector('[data-math="0"]').click();assert.equal(e.eval('p.tasks[0].question'),String.raw`$\frac{a}{b}$`)});
