const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
// Minimal DOM test double: tests runtime state transitions without browser dependencies.
class Element{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.children=[];this.parent=null;this.style={setProperty(k,v){this[k]=v}};this.dataset={};this.disabled=false;this.clientWidth=600;this.clientHeight=400;for(const [k,v] of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.className=attrs.class||'';this.id=attrs.id||'';this.classList={toggle:(name,on)=>{const s=new Set(this.className.split(' '));on?s.add(name):s.delete(name);this.className=[...s].join(' ')}};}
 set innerHTML(html){this.children=[];this.html=html;const stack=[this],re=/<(\/)?([\w-]+)([^>]*?)>/g;let m;while((m=re.exec(html))){if(m[1]){if(stack.length>1)stack.pop();continue}const attrs={};const ar=/([\w-]+)="([^"]*)"/g;let a;while((a=ar.exec(m[3])))attrs[a[1]]=a[2];const el=new Element(m[2],attrs);stack.at(-1).append(el);if(!['img','input','br','meta','hr'].includes(m[2])&&!m[3].endsWith('/'))stack.push(el)}}
 get innerHTML(){return this.html||''}append(el){el.parent=this;this.children.push(el)}remove(){if(this.parent)this.parent.children=this.parent.children.filter(e=>e!==this)}
 setAttribute(k,v){this.attrs[k]=v}getBoundingClientRect(){return {left:0,top:0,width:600,height:400}}addEventListener(){}focus(){this.focused=true}
 matches(s){s=s.trim();if(s.startsWith('.'))return this.className.split(' ').includes(s.slice(1));if(s.startsWith('#'))return this.id===s.slice(1);if(s.startsWith('['))return Object.hasOwn(this.attrs,s.slice(1,-1));return this.tagName.toLowerCase()===s}
 querySelectorAll(s){const out=[];const selectors=s.split(',');const walk=n=>{for(const c of n.children){if(selectors.some(s=>c.matches(s)))out.push(c);walk(c)}};walk(this);return out}
 querySelector(s){return this.querySelectorAll(s)[0]||null}
}
function setup(overrides={}){const host=new Element(),timeouts=[],intervals=[];const document={getElementById:()=>host,createElement:tag=>new Element(tag)};const context=vm.createContext({document,console,parent:{postMessage(){}},ResizeObserver:class{observe(){}},setTimeout:fn=>{timeouts.push(fn);return timeouts.length},clearTimeout(){},setInterval:fn=>{intervals.push(fn);return intervals.length},clearInterval(){},Audio:class{play(){return Promise.resolve()}},...overrides});context.window=context;context.addEventListener=()=>{};vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/core.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/game.js'),'utf8'),context);const p=context.DiffCore.project();p.titleScreen.enabled=false;p.images.a=p.images.b={source:'data:image/png;base64,a',naturalWidth:600,naturalHeight:400};const id='difference',t=context.DiffCore.task(id);Object.assign(t,{question:'Question',answers:['Yes','No'],correctIndexes:[0]});p.tasks=[t];p.differences=[{id,shape:'rect',x:.5,y:.5,w:.2,h:.2,linkedTaskId:t.id,difficulty:'normal'}];return {host,p,context,timeouts,intervals,run(){context.mountGame(p,'play','game')},click(x=.5,y=.5,index=0){host.querySelectorAll('.image-inner')[index].onclick({clientX:x*600,clientY:y*400})},answer(i=0){host.querySelectorAll('.answer').find(e=>Number(e.dataset.index)===i).onclick();host.querySelector('#submit').onclick()},flush(){while(timeouts.length)timeouts.shift()()}}}
test('correct answer wins with one remaining life and both images recognize zones',()=>{for(const index of [0,1]){const g=setup();g.p.hud.lives=1;g.run();g.click(.5,.5,index);assert.ok(g.host.querySelector('.modal'));g.answer();g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'));assert.ok(g.host.innerHTML.includes('♥ 1'));}});
test('wrong answer loses the last life before completion',()=>{const g=setup();g.p.hud.lives=1;g.run();g.click();g.answer(1);assert.ok(g.host.innerHTML.includes('Попробуем ещё раз?'));assert.equal(g.host.querySelector('.modal'),null)});
test('wrong answer without life penalty allows retry and eventual victory',()=>{const g=setup();g.p.tasks[0].loseLife=false;g.run();g.click();g.answer(1);assert.ok(g.host.querySelector('.modal'));g.answer(0);g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'));assert.ok(g.host.innerHTML.includes('♥ 3'))});
test('false-click penalty modes preserve, decrease lives or decrease points',()=>{for(const mode of ['none','life','points']){const g=setup();g.p.hud.penalty=mode;g.run();g.click(.01,.01);assert.equal(g.host.querySelector('.modal'),null);assert.ok(g.host.querySelector('.hud').innerHTML.includes(mode==='life'?'♥♥':'♥♥♥'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('★ 0'));}});
test('countdown expiry causes defeat and task pause prevents expiry',()=>{const g=setup();g.p.hud.timer='countdown';g.p.hud.seconds=1;g.run();g.click();g.intervals[0]();assert.ok(g.host.querySelector('.modal'));g.p.hud.pause=false;g.intervals[0]();assert.ok(g.host.innerHTML.includes('Попробуем ещё раз?'))});
test('repeat click on completed difference cannot award points twice',()=>{const g=setup();const id='second',t=g.context.DiffCore.task(id);t.question='Second';t.answers=['Yes','No'];g.p.tasks.push(t);g.p.differences.push({id,shape:'rect',x:.1,y:.1,w:.1,h:.1,linkedTaskId:t.id,difficulty:'normal'});g.run();g.click();g.answer();g.flush();g.click();assert.equal(g.host.querySelector('.modal'),null);assert.ok(g.host.querySelector('.hud').innerHTML.includes('★ 10'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('1/2'))});
test('oral confirmation requires two clicks when enabled',()=>{const g=setup();g.p.tasks[0].type='oral';g.p.tasks[0].oralConfirm=true;g.run();g.click();g.host.querySelector('#submit').onclick();assert.ok(g.host.querySelector('.modal'));g.host.querySelector('#submit').onclick();g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'))});
test('runtime never mutates the editor project',()=>{const g=setup();const before=JSON.stringify(g.p);g.run();g.click();g.answer();g.flush();assert.equal(JSON.stringify(g.p),before)});
