const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
// Minimal DOM test double: tests runtime state transitions without browser dependencies.
const {Element}=require('./dom.cjs');
function setup(overrides={}){const host=new Element(),timeouts=[],intervals=[];const document={getElementById:()=>host,createElement:tag=>new Element(tag)};const context=vm.createContext({document,console,parent:{postMessage(){}},ResizeObserver:class{observe(){}},setTimeout:fn=>{timeouts.push(fn);return timeouts.length},clearTimeout(){},setInterval:fn=>{intervals.push(fn);return intervals.length},clearInterval(){},Audio:class{play(){return Promise.resolve()}},...overrides});context.window=context;context.addEventListener=()=>{};vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/core.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/game.js'),'utf8'),context);const p=context.DiffCore.project();p.titleScreen.enabled=false;p.images.a=p.images.b={source:'data:image/png;base64,a',naturalWidth:600,naturalHeight:400};const id='difference',t=context.DiffCore.task(id);Object.assign(t,{question:'Question',answers:['Yes','No'],correctIndexes:[0]});p.tasks=[t];p.differences=[{id,shape:'rect',x:.5,y:.5,w:.2,h:.2,linkedTaskId:t.id,difficulty:'normal'}];return {host,p,context,timeouts,intervals,run(){context.mountGame(p,'play','game')},click(x=.5,y=.5,index=0){host.querySelectorAll('.image-inner')[index].onclick({clientX:x*600,clientY:y*400})},answer(i=0){host.querySelectorAll('.answer').find(e=>Number(e.dataset.index)===i).onclick();host.querySelector('#submit').onclick()},flush(){while(timeouts.length)timeouts.shift()()}}}
test('correct answer wins with one remaining life and both images recognize zones',()=>{for(const index of [0,1]){const g=setup();g.p.hud.lives=1;g.run();g.click(.5,.5,index);assert.ok(g.host.querySelector('.modal'));g.answer();g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'));assert.ok(g.host.innerHTML.includes('♥ 1'));}});
test('wrong answer loses the last life before completion',()=>{const g=setup();g.p.hud.lives=1;g.run();g.click();g.answer(1);assert.ok(g.host.innerHTML.includes('Попробуем ещё раз?'));assert.equal(g.host.querySelector('.modal'),null)});
test('wrong answer without life penalty allows retry and eventual victory',()=>{const g=setup();g.p.tasks[0].loseLife=false;g.run();g.click();g.answer(1);assert.ok(g.host.querySelector('.modal'));g.answer(0);g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'));assert.ok(g.host.innerHTML.includes('♥ 3'))});
test('false-click penalty modes preserve, decrease lives or decrease points',()=>{for(const mode of ['none','life','points']){const g=setup();g.p.hud.penalty=mode;g.run();g.click(.01,.01);assert.equal(g.host.querySelector('.modal'),null);assert.ok(g.host.querySelector('.hud').innerHTML.includes(mode==='life'?'♥♥':'♥♥♥'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('★ 0'));}});
test('countdown ends with a time-up screen without spending lives and respects task pause',()=>{const g=setup();g.p.hud.timer='countdown';g.p.hud.seconds=1;g.run();g.click();g.intervals[0]();assert.ok(g.host.querySelector('.modal'));g.p.hud.pause=false;g.intervals[0]();assert.ok(g.host.innerHTML.includes('Время вышло'));assert.ok(g.host.innerHTML.includes('♥ 3'))});
test('repeat click on completed difference cannot award points twice',()=>{const g=setup();const id='second',t=g.context.DiffCore.task(id);t.question='Second';t.answers=['Yes','No'];g.p.tasks.push(t);g.p.differences.push({id,shape:'rect',x:.1,y:.1,w:.1,h:.1,linkedTaskId:t.id,difficulty:'normal'});g.run();g.click();g.answer();g.flush();g.click();assert.equal(g.host.querySelector('.modal'),null);assert.ok(g.host.querySelector('.hud').innerHTML.includes('★ 10'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('1/2'))});
test('oral confirmation requires two clicks when enabled',()=>{const g=setup();g.p.tasks[0].type='oral';g.p.tasks[0].oralConfirm=true;g.run();g.click();g.host.querySelector('#submit').onclick();assert.ok(g.host.querySelector('.modal'));g.host.querySelector('#submit').onclick();g.flush();assert.ok(g.host.innerHTML.includes('Прекрасная работа!'))});
test('runtime never mutates the editor project',()=>{const g=setup();const before=JSON.stringify(g.p);g.run();g.click();g.answer();g.flush();assert.equal(JSON.stringify(g.p),before)});
test('spending a life from two to one does not end the game',()=>{const g=setup();g.p.hud.lives=2;g.run();g.click();g.answer(1);assert.ok(g.host.querySelector('.modal'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('♥'));assert.ok(!g.host.innerHTML.includes('Попробуем ещё раз?'));g.answer(1);assert.ok(g.host.innerHTML.includes('Попробуем ещё раз?'));assert.ok(g.host.innerHTML.includes('♥ 0'))});
test('victory never offers a title-screen button even for legacy projects',()=>{const g=setup();g.p.finalScreens.showTitle=true;g.p.finalScreens.win.button.label='Ещё приключение';g.p.finalScreens.win.button.background='#ff8800';g.p.finalScreens.win.button.glow=24;g.run();g.click();g.answer();g.flush();assert.equal(g.host.querySelector('#title'),null);assert.ok(g.host.innerHTML.includes('Ещё приключение'));assert.ok(g.host.innerHTML.includes('background:#ff8800'));assert.ok(g.host.innerHTML.includes('0 0 24px'))});
test('title background opacity and text sizes do not fade the button or letters',()=>{const g=setup();g.p.titleScreen.enabled=true;g.p.titleScreen.backgroundOpacity=30;g.p.titleScreen.titleSize=72;g.p.titleScreen.textSize=28;g.p.titleScreen.button.label='Вперёд в мастерскую';g.run();const bg=g.host.querySelector('.screen-backdrop');assert.ok(bg.attrs.style.includes('opacity:0.3'));assert.ok(!g.host.querySelector('.center').attrs.style);assert.ok(g.host.innerHTML.includes('72px'));assert.ok(g.host.innerHTML.includes('28px'));assert.ok(g.host.innerHTML.includes('Вперёд в мастерскую'))});
test('hint color, glow and custom quantity are used in runtime',()=>{const g=setup();g.p.hud.hints=25;g.p.hud.hintButton.background='#556677';g.p.hud.hintButton.glow=18;g.run();assert.ok(g.host.querySelector('#hint').attrs.style.includes('background:#556677'));assert.ok(g.host.querySelector('#hint').attrs.style.includes('0 0 18px'));assert.ok(g.host.querySelector('.hud').innerHTML.includes('Подсказка 25'));g.host.querySelector('#hint').onclick();assert.ok(g.host.querySelector('.hud').innerHTML.includes('Подсказка 24'))});
